// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU-om8QWRruysHRLKoqZaBP4bEh2KhruM',
    appId: '1:109392965339:web:1a687d9e85bafd26c926fe',
    messagingSenderId: '109392965339',
    projectId: 'lab6-e3b70',
    authDomain: 'lab6-e3b70.firebaseapp.com',
    databaseURL: 'https://lab6-e3b70-default-rtdb.firebaseio.com',
    storageBucket: 'lab6-e3b70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfEZjq3_s1vt8yjEuVYJ71LJoFPFn7D1w',
    appId: '1:109392965339:android:0889496ead9c41cbc926fe',
    messagingSenderId: '109392965339',
    projectId: 'lab6-e3b70',
    databaseURL: 'https://lab6-e3b70-default-rtdb.firebaseio.com',
    storageBucket: 'lab6-e3b70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-B2xNFszJ1RVLZE1-01u2MSrXLGoag4',
    appId: '1:109392965339:ios:00730675c8299580c926fe',
    messagingSenderId: '109392965339',
    projectId: 'lab6-e3b70',
    databaseURL: 'https://lab6-e3b70-default-rtdb.firebaseio.com',
    storageBucket: 'lab6-e3b70.appspot.com',
    iosBundleId: 'com.example.beybicoAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU-om8QWRruysHRLKoqZaBP4bEh2KhruM',
    appId: '1:109392965339:web:1d15ed9b16255932c926fe',
    messagingSenderId: '109392965339',
    projectId: 'lab6-e3b70',
    authDomain: 'lab6-e3b70.firebaseapp.com',
    databaseURL: 'https://lab6-e3b70-default-rtdb.firebaseio.com',
    storageBucket: 'lab6-e3b70.appspot.com',
  );
}
